version: '3'
services:
  db:
    restart: always
    image: postgres:11
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yelp
    ports:
      - '5432:5432'
    volumes: 
      - ./docker/data/db:/var/lib/postgres
  app:
    env_file: .env 
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db